---
version: "3.8"
services:
  envoy-ingress:
    image: envoyproxy/envoy:v1.22-latest
    restart: always
    ports:
    - 80:80
    - 9901:9901
    volumes:
      - ./envoy-ingress.yaml:/etc/envoy/envoy.yaml
      - ./dynamic_config:/var/lib/envoy
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "ENVOY_UID=0"
      - TZ=Asia/Shanghai
    command: envoy -c /etc/envoy/envoy.yaml --base-id 1
    depends_on:
      - heimdall
      - grafana
      - portainer
    networks:
      haydenmesh: {}
    dns: 
      - 192.168.31.199

  heimdall:
    image: linuxserver/heimdall:latest
    restart: always
    deploy:
      replicas: 2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /opt/ingressgateway-envoy/heimdall/config:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      haydenmesh: {}
    dns: 
      - 192.168.31.199

  grafana:
    image: grafana/grafana-oss:main-ubuntu
    restart: always
    deploy: 
      replicas: 2
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/ingressgateway-envoy/grafana/grafana_data:/var/lib/grafana
      - /opt/ingressgateway-envoy/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /etc/localtime:/etc/localtime:ro
    user: '472'
    networks:
      haydenmesh: {}
    dns: 
      - 192.168.31.199

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    environment:
      - UUID=0
      - GUID=0
      - TZ=Asia/Shanghai
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - /opt/ingressgateway-envoy/portainer/portainer_data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      haydenmesh: {}
    dns: 
      - 192.168.31.199
    cap_add:
      - ALL

  ariang:
    image: nginx:latest
    restart: always
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - "/opt/ingressgateway-envoy/ariang/index.html:/usr/share/nginx/html/index.html"
      - "/opt/ingressgateway-envoy/ariang/font-awesome/fontawesome-webfont.woff2:/usr/share/nginx/html/fonts/fontawesome-webfont.woff2"
      - /etc/localtime:/etc/localtime:ro
    dns:
      - 192.168.31.199
    networks:
      haydenmesh: {}

  statsd_exporter:
    image: prom/statsd-exporter:latest
    restart: always
    network_mode: "host"

  jeager:
    image: jaegertracing/all-in-one:latest
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - /opt/ingressgateway-envoy/portainer/portainer_data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      haydenmesh: {}
    ports:
     - 6831:6831/udp
     - 6832:6832/udp
     - 5778:5778
     - 16686:16686
     - 4317:4317
     - 4318:4318
     - 14250:14250
     - 14268:14268
     - 14269:14269
     - 9411:9411

networks:
  haydenmesh: 
    driver: bridge
    external: true
