node:
  cluster: haydenrpi4
  id: haydenrpi4

admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

dynamic_resources:
  cds_config:
    resource_api_version: "V3"
    path_config_source: 
      path: /var/lib/envoy/cds.yaml
  lds_config:
    resource_api_version: "V3"
    path_config_source: 
      path: /var/lib/envoy/lds.yaml
