node:
  cluster: haydenrpi4
  id: haydenrpi4

    # tracing:
    #   http:
    #     name: envoy.zipkin
    #     config:
    #       collector_cluster: jaeger
    #       collector_endpoint: "/api/v1/spans"

admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

dynamic_resources:
  cds_config:
    resource_api_version: "V3"
    path_config_source: 
      path: /var/lib/envoy/cds.yaml
  lds_config:
    resource_api_version: "V3"
    path_config_source: 
      path: /var/lib/envoy/lds.yaml

stats_sinks:
  - name: envoy.stat_sinks.statsd
    typed_config: 
      "@type": type.googleapis.com/envoy.config.metrics.v3.StatsdSink
      address: 
        socket_address: 
          address: 192.168.31.199
          port_value: 9125
      prefix: envoy-ingress

